import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml", "~/.config/alacritty/font-size.toml", "~/.local/share/omakub/defaults/alacritty.toml" ]

[window]
startup_mode = "Maximized"
title = "Roger's Terminal"
option_as_alt = "Both"

[selection]
save_to_clipboard = true

[shell]
program = "/usr/local/bin/bash"
args = ["--login", "-c", "zellij -l welcome"]

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
command = "/usr/bin/open"
hyperlinks = true
post_processing = true
mouse.enabled = true
mouse.mods = "Command"
